# Generated by Django 3.2.7 on 2021-09-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Apartment', 'Apartment')], default='House', max_length=10),
        ),
    ]
